Displaying resource type when deleting item
sensu/sensu-go pull request #4358
Opened 2021-07-19 10:17 UTC by agm650

Signed-off-by: Luc Dandoy <luc.dandoy@gmail.com>

## What is this change?

Displaying resource type in the deletion confirmation prompt.

## Why is this change necessary?

Proposal to fix #3812.

## Does your change need a Changelog entry?

An entry was added to the changelog file

## Do you need clarification on anything?

No.

## Were there any complications while making this change?

Not really. Not sure if my fix is the most "efficient"/"beautiful" one

## Have you reviewed and updated the documentation for this change? Is new documentation required?

I don't think so as it's mainly a "cosmetic" change

## How did you verify this change?

I've been deleting various resource on a test environment to check if the new prompt was correctly displayed.

## Is this change a patch?

no

2021-07-26 15:58 UTC, echlebek requested changes
I like the change! A small nit, it should be "ConfirmDeleteResource", not "ConfirmDeleteRessource". Would you mind fixing that? Thanks!

2021-07-26 16:03 UTC, agm650 commented
I'll do that and update the request

2021-07-27 17:52 UTC, echlebek commented on cli/commands/clusterrole/delete.go
> +				if confirmed := helpers.ConfirmDeleteResource(name, "clutser-role"); !confirmed {
Oops, one more typo here!

2021-07-28 08:27 UTC, agm650 commented on cli/commands/clusterrole/delete.go
> +				if confirmed := helpers.ConfirmDeleteResource(name, "clutser-role"); !confirmed {
solved!

2021-07-29 18:25 UTC, echlebek approved these changes

2021-08-03 19:05 UTC, merged