Add flag to configure API & dashboard's write timeouts
sensu/sensu-go pull request #4474
Opened 2021-11-01 22:39 UTC by jamesdphillips

Adds `api-write-timeout` & `dashboard-write-timeout` flags to allow users to configure the respective HTTP server's write timeout. Useful when some requests might reasonably take more than a few seconds to complete.

---

Signed-off-by: James Phillips <jamesdphillips@gmail.com>

2021-11-01 23:57 UTC, amdprophet approved these changes

2021-11-02 16:34 UTC, ccressent reviewed
I thought we were sort of standardizing on using `time.Duration` for these types of flags going forward? Then the flag can take values like `5ms`, `15s`, ...

2021-11-02 16:39 UTC, echlebek commented
Yes please @ccressent! I think using the string representation of time.Duration should be our standard, considering it has first class support in our argument parser.

2021-11-02 18:09 UTC, amdprophet requested changes

2021-11-02 18:09 UTC, amdprophet commented on backend/cmd/start.go
> +		flagSet.Int64(flagAPIWriteTimeout, viper.GetInt64(flagAPIWriteTimeout), "maximum duration before timing out writes of responses")
As the others have mentioned, let's use `viper.GetDuration()` here instead and update the types surrounding this flag to `time.Duration`.

2021-11-02 20:38 UTC, jamesdphillips commented
@ccressent good call! updated to use `GetDuration`.

2021-11-02 20:40 UTC, jamesdphillips commented
Bit of a bummer but I can't think of an easy way to migrate `--agent-write-timeout` to use a duration. If we care about compatibility of `backend.Config` that is.

2021-11-02 20:53 UTC, echlebek commented
@jamesdphillips yeah it's fine to leave it as is. We can add it to the list of things we want to break with 7.x...

2021-11-04 18:37 UTC, amdprophet approved these changes

2021-11-09 17:49 UTC, ccressent approved these changes

2021-11-10 20:09 UTC, merged