Update tessend to not use etcd
sensu/sensu-go pull request #4949
Opened 2023-01-30 14:05 UTC by ccressent

## What is this change?

This updates `tessend` to make it not use etcd at all.

## Why is this change necessary?

7.x work to get rid of etcd

## Does your change need a Changelog entry?

I think it's already covered under the entry that says that etcd is not used/supported anymore in 7.x.
So not adding an entry.

## Do you need clarification on anything?

There is still a TODO related to figuring out the number of backends in the cluster. I'm not sure what is the current best way to go about retrieving or figuring out this information. I thought I might be able to leverage the new OPC work, but it's not clear I can after all.

## Were there any complications while making this change?

Many pieces of `tessend` were hardcoded to read/write keys in etcd, and many other moving pieces were necessary to complete this work (new store counting and watching methods, ...).

## Have you reviewed and updated the documentation for this change? Is new documentation required?

No documentation update needed: the user facing interface that lets one enable/disable `tessend` is not changing. This change is purely about how `tessend` works _internally_.

## How did you verify this change?

Manual testing, the old tests need to be reintroduced/reworked based on their relevance.

## Is this change a patch?

No.

2023-01-31 19:05 UTC, echlebek requested changes
It's looking good to me, the only issue is that some of the types are special now and don't come from the config store, but rather from other stores. So they need to be explicitly handled unfortunately.

2023-01-31 19:05 UTC, echlebek commented on backend/tessend/data.go
> +	StateStore string `json:"state_store"`
We're no longer creating a distinction between these stores. Rather there is the config store, and then several specific stores for special types. These include events, entities, entity configs, entity states, and namespaces.

2023-01-31 19:05 UTC, echlebek commented on backend/tessend/tessend.go
> +	// for which we don't really have an abstraction yet.
Christian added support for listing OPC items recently, so we can incorporate that now

2023-01-31 19:05 UTC, echlebek commented on backend/tessend/tessend.go
> +		count, err := t.store.GetConfigStore().Count(t.ctx, storev2.NewResourceRequestFromV2Resource(resource))
This will be a bit of an issue for the "special" data types unfortunately, since they need to come from their respective store.

2023-02-06 21:06 UTC, c-kruse reviewed
Cluster Member count looks right to me!

The note Eric pointed out regarding the special types still looks outstanding, though. I think functioning counters Events and Entities probably two of most essential bits of tessen. Other than that, ✅ .

2023-02-28 17:25 UTC, echlebek commented on backend/tessend/data.go
> +	StateStore string `json:"state_store"`
I see, OK

2023-02-28 17:25 UTC, echlebek approved these changes

2023-03-06 21:51 UTC, merged